name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches: [ main, chore/footnote-audit-fixes-2025-09-05 ]   # include your feature branch for now
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install MkDocs deps
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install mkdocs mkdocs-material
          fi

      - name: Build & deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mkdocs gh-deploy --force --clean --strict
